AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Catalog: Docker Notebook EC2'
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E7001
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Linux Instance Configuration
        Parameters:
          - EC2InstanceType
          - NotebookType
          - VolumeSize
    ParameterLabels:
      EC2InstanceType:
        default: EC2 Instance Type
      NotebookType:
        default: Notebook Type
      VolumeSize:
        default: Disk Size

Mappings:
  AccountToImportParams:
    'Fn::Transform':
      Name: 'AWS::Include'
      Parameters:
        # include is @ https://github.com/Sage-Bionetworks/admincentral-infra/blob/master/templates/cfn-service-catalog-snippets.yaml
        Location: s3://cfn-snippets-bucket-cloudformationsnippetsbucket-elu83sv8ocdz/scipool-sc-lib-infra/ScAccountToExportMappping.yaml
  NotebookTypeToInitParams:
    Jupyter:
      NoteBookTypeForDocker: jupyter
      ConfigSet: StartContainersJupyter
      DockerImage: quay.io/jupyter/base-notebook:python-3.11
      EC2WorkDir: /home/ssm-user/workdir
    Rstudio:
      NoteBookTypeForDocker: rstudio
      ConfigSet: StartContainersRstudio
      DockerImage: rocker/rstudio:4.3.2
      EC2WorkDir: /home/ssm-user/workdir
  GlobalVars:
    DockerNetworkName:
      Value: proxy-net
    NotebookContainerName:
      Value: notebook
    SSMParameterPrefix:
      Value: service-catalog/synapse/cred
    SSMParameterSuffix:
      Value: oidc-accesstoken

Parameters:

  EC2InstanceType:
    AllowedValues:
      - t3a.nano
      - t3a.micro
      - t3a.small
      - t3a.medium
      - t3a.large
      - t3a.xlarge
      - t3a.2xlarge
      - m6a.large
      - m6a.xlarge
      - m6a.2xlarge
      - m6a.4xlarge
      - m6a.8xlarge
      - c6a.large
      - c6a.xlarge
      - c6a.2xlarge
      - c6a.4xlarge
      - c6a.8xlarge
      - r6a.large
      - r6a.xlarge
      - r6a.2xlarge
      - r6a.4xlarge
      - r6a.8xlarge
      - g5.xlarge
      - g5.2xlarge
      - g5.4xlarge
    Default: t3a.small
    Description: Amazon EC2 Instance Type
    Type: String

  NotebookType:
    Type: String
    Description: Type of notebook software to install
    Default: Rstudio
    AllowedValues:
      - Rstudio
      - Jupyter

  VolumeSize:
    Description: The EC2 volume size (in GB)
    Type: Number
    Default: 50
    MinValue: 50
    MaxValue: 2000

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-essentials-TagRootVolumePolicy'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-cfn-tag-instance-policy-TagInstancePolicy'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-get-role-policy-ReadAssumedRoleInformationPolicy'
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore' #For maintenance tasks
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-product-ec2-linux-notebook-write-to-ssm-policy-WriteToSSMPolicy'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com #For maintenance service
            Action:
              - sts:AssumeRole

  NotebookConnectSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W1011
    Properties:
      GroupDescription: 'Add ingress to 443 from notebook connection ALB'
      VpcId: !ImportValue
        'Fn::FindInMap': [AccountToImportParams, !Ref "AWS::AccountId", VPCId]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !ImportValue
            'Fn::Sub': '${AWS::Region}-alb-notebook-access-ALBSecurityGroup'

  TgwHubSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W1011
    Properties:
      GroupDescription: 'Allow network access from TGW Hub'
      VpcId: !ImportValue
        'Fn::FindInMap': [AccountToImportParams, !Ref "AWS::AccountId", VPCId]
      SecurityGroupIngress:
        - CidrIp: "10.50.0.0/16"
          FromPort: -1
          ToPort: -1
          IpProtocol: "-1"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref 'InstanceRole'

  # The EC2 instance writes to it, but this is introduced for the cleanup of the parameter
  InstanceSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${SSMParameterPrefix}/${LinuxInstance}/${SSMParameterSuffix}"
        - SSMParameterPrefix:
            'Fn::FindInMap': [GlobalVars, SSMParameterPrefix, Value]
          SSMParameterSuffix:
            'Fn::FindInMap': [GlobalVars, SSMParameterSuffix, Value]
      Type: String
      Value: to be replaced by EC2

  SSMParameterEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: key used to encrypt SSM Parameters for a EC2 instance
      # number of days to wait before key gets deleted
      PendingWindowInDays: 7
      EnableKeyRotation: "true"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
        # https://dev.to/jansonsa/aws-how-to-deny-access-to-resources-while-allowing-a-specific-role-547b
          - Sid: "Deny decrypt to all Principals that shouldn't require access"
            Effect: 'Deny'
            Principal: "*"
            Condition:
              StringNotEquals:
                "aws:PrincipalArn": !Sub "${InstanceRole.Arn}"
            Action:
              - kms:Decrypt
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: !Sub "${InstanceRole.Arn}"
            Action:
              - kms:DescribeKey
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey
              - kms:GenerateDataKeyWithoutPlaintext
            Resource: '*'
          - Sid: 'Default KMS Policy that enables IAM permissions'  # https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html#key-policy-default
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:*'
            Resource: '*'
          - Sid: "Allow administration of the key to CFN service role"
            Effect: "Allow"
            Principal:
              AWS:
                - !ImportValue
                  'Fn::Sub': '${AWS::Region}-sc-ec2vpc-launchrole-LaunchRoleArn'
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"

  SSMParameterEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub
        - 'alias/${SSMParameterPrefix}/${LinuxInstance}'
        - SSMParameterPrefix:
            'Fn::FindInMap': [GlobalVars, SSMParameterPrefix, Value]
      TargetKeyId: !Ref SSMParameterEncryptionKey

  LinuxInstance:
    Type: AWS::EC2::Instance
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E1022
            - W1011
      'AWS::CloudFormation::Init':
        configSets:
          StartContainersJupyter:
            - set_env_vars
            - start_docker_network
            - start_reverse_proxy
            - make_work_dir
            - start_jupyter_notebook
          StartContainersRstudio:
            - set_env_vars
            - start_docker_network
            - start_reverse_proxy
            - make_work_dir
            - start_rstudio_notebook
        set_env_vars:
          files:
            /opt/sage/bin/make_env_vars_file.sh:
              source: "https://raw.githubusercontent.com/Sage-Bionetworks/service-catalog-utils/v2.0.3/linux/opt/sage/bin/make_env_vars_file.sh"
              mode: "00744"
              owner: "root"
              group: "root"
          commands:
            make_env_vars_file:
              command: "/bin/bash /opt/sage/bin/make_env_vars_file.sh"
              env:
                AWS_REGION: !Ref AWS::Region
                STACK_NAME: !Ref AWS::StackName
                STACK_ID: !Ref AWS::StackId
        start_docker_network:
          commands:
            start_docker_network:
              command: >
                docker network inspect ${NETWORK_NAME} ||
                docker network create --driver bridge ${NETWORK_NAME}
              env:
                NETWORK_NAME:
                  'Fn::FindInMap': [GlobalVars, DockerNetworkName, Value]
        start_reverse_proxy:
          commands:
            start_reverse_proxy:
              # For idempotency this command tries to restart an existing container and only creates one if that fails.
              command: |
                TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
                EC2_INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-id)
                docker start reverse-proxy || \
                docker run -d -p 443:443 --memory=1g --cpus=1 \
                --name reverse-proxy \
                --network ${NETWORK_NAME} \
                --restart unless-stopped \
                -e EC2_INSTANCE_ID=${EC2_INSTANCE_ID} \
                -e NOTEBOOK_HOST=${NOTEBOOK_CONTAINER_NAME} \
                -e AWS_REGION=${AWS_REGION} \
                -e SERVICE_CATALOG_PREFIX=${SERVICE_CATALOG_PREFIX} \
                -e SSM_PARAMETER_SUFFIX=${SSM_PARAMETER_SUFFIX} \
                ghcr.io/sage-bionetworks-it/notebook-reverse-proxy-${NOTEBOOK_TYPE}:v1.0.1
              env:
                AWS_REGION: !Ref AWS::Region
                NETWORK_NAME:
                  'Fn::FindInMap': [GlobalVars, DockerNetworkName, Value]
                NOTEBOOK_CONTAINER_NAME:
                  'Fn::FindInMap': [GlobalVars, NotebookContainerName, Value]
                SERVICE_CATALOG_PREFIX:
                  'Fn::FindInMap': [GlobalVars, SSMParameterPrefix, Value]
                SSM_PARAMETER_SUFFIX:
                  'Fn::FindInMap': [GlobalVars, SSMParameterSuffix, Value]
                NOTEBOOK_TYPE:
                  'Fn::FindInMap': [NotebookTypeToInitParams, !Ref NotebookType, NoteBookTypeForDocker]
        make_work_dir:
          commands:
            make_work_dir:
              command: |
                mkdir -p ${EC2_WORK_DIR}
                sudo chmod 777 ${EC2_WORK_DIR}
              env:
                EC2_WORK_DIR:
                  'Fn::FindInMap': [NotebookTypeToInitParams, !Ref NotebookType, EC2WorkDir]
        start_jupyter_notebook:
          commands:
            start_notebook:
              command: |
                TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
                EC2_INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-id)
                SYNAPSE_TOKEN_AWS_SSM_PARAMETER_NAME=/${SERVICE_CATALOG_PREFIX}/${EC2_INSTANCE_ID}/${SSM_PARAMETER_SUFFIX}
                # For idempotency this command tries to restart an existing container and only creates one if that fails.
                docker start ${NOTEBOOK_CONTAINER_NAME} || \
                docker run -d --name ${NOTEBOOK_CONTAINER_NAME} \
                --restart unless-stopped \
                -e DOCKER_STACKS_JUPYTER_CMD=notebook \
                -e SYNAPSE_TOKEN_AWS_SSM_PARAMETER_NAME=${SYNAPSE_TOKEN_AWS_SSM_PARAMETER_NAME} \
                -e AWS_DEFAULT_REGION=${AWS_REGION} \
                -v ${EC2_WORK_DIR}:${JUPYTER_WORK_DIR} \
                --network ${NETWORK_NAME} ${DOCKER_IMAGE} \
                bash -c "start-notebook.py --IdentityProvider.token='' --NotebookApp.base_url=/${EC2_INSTANCE_ID} \
                --notebook-dir=${JUPYTER_WORK_DIR}"
              env:
                NETWORK_NAME:
                  'Fn::FindInMap': [GlobalVars, DockerNetworkName, Value]
                NOTEBOOK_CONTAINER_NAME:
                  'Fn::FindInMap': [GlobalVars, NotebookContainerName, Value]
                EC2_WORK_DIR:
                  'Fn::FindInMap': [NotebookTypeToInitParams, !Ref NotebookType, EC2WorkDir]
                DOCKER_IMAGE:
                  'Fn::FindInMap': [NotebookTypeToInitParams, !Ref NotebookType, DockerImage]
                JUPYTER_WORK_DIR: /home/jovyan/workdir
                SERVICE_CATALOG_PREFIX:
                  'Fn::FindInMap': [GlobalVars, SSMParameterPrefix, Value]
                SSM_PARAMETER_SUFFIX:
                  'Fn::FindInMap': [GlobalVars, SSMParameterSuffix, Value]
                AWS_REGION:
                  'Fn::Sub': ${AWS::Region}
        start_rstudio_notebook:
          commands:
            start_notebook:
              command: |
                TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
                EC2_INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-id)
                SYNAPSE_TOKEN_AWS_SSM_PARAMETER_NAME=/${SERVICE_CATALOG_PREFIX}/${EC2_INSTANCE_ID}/${SSM_PARAMETER_SUFFIX}
                # For idempotency this command tries to restart an existing container and only creates one if that fails.
                docker start ${NOTEBOOK_CONTAINER_NAME} || \
                docker run -d --name ${NOTEBOOK_CONTAINER_NAME} \
                --restart unless-stopped \
                --network ${NETWORK_NAME} \
                -e DISABLE_AUTH=true \
                -e SYNAPSE_TOKEN_AWS_SSM_PARAMETER_NAME=${SYNAPSE_TOKEN_AWS_SSM_PARAMETER_NAME} \
                -e AWS_DEFAULT_REGION=${AWS_REGION} \
                -v ${EC2_WORK_DIR}:${RSTUDIO_WORK_DIR} \
                ${DOCKER_IMAGE}
              env:
                NETWORK_NAME:
                  'Fn::FindInMap': [GlobalVars, DockerNetworkName, Value]
                NOTEBOOK_CONTAINER_NAME:
                  'Fn::FindInMap': [GlobalVars, NotebookContainerName, Value]
                DOCKER_IMAGE:
                  'Fn::FindInMap': [NotebookTypeToInitParams, !Ref NotebookType, DockerImage]
                EC2_WORK_DIR:
                  'Fn::FindInMap': [NotebookTypeToInitParams, !Ref NotebookType, EC2WorkDir]
                RSTUDIO_WORK_DIR: /home/rstudio
                SERVICE_CATALOG_PREFIX:
                  'Fn::FindInMap': [GlobalVars, SSMParameterPrefix, Value]
                SSM_PARAMETER_SUFFIX:
                  'Fn::FindInMap': [GlobalVars, SSMParameterSuffix, Value]
                AWS_REGION:
                  'Fn::Sub': ${AWS::Region}
    Properties:
      ImageId: "ami-0b710e028cd5ff838" # https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-jammy/tree/v1.0.0
      InstanceType: !Ref 'EC2InstanceType'
      SubnetId: !ImportValue
          'Fn::FindInMap': [AccountToImportParams, !Ref "AWS::AccountId", PrivateSubnet]
      SecurityGroupIds:
        - !ImportValue
          'Fn::FindInMap': [AccountToImportParams, !Ref "AWS::AccountId", VpnSecurityGroup]
        - !Ref NotebookConnectSecurityGroup
        - !Ref TgwHubSecurityGroup
      KeyName: 'scipool'
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            DeleteOnTermination: true
            VolumeSize: !Ref VolumeSize
            Encrypted: true
      IamInstanceProfile: !Ref 'InstanceProfile'
      UserData:
        Fn::Base64: !Sub
          -  |
            #!/bin/bash
            cfn-init -v --stack ${AWS::StackName} --resource LinuxInstance --configsets ${ConfigSet} --region ${AWS::Region}
            cfn-signal -e $? --stack ${AWS::StackName} --resource LinuxInstance --region ${AWS::Region}
          - ConfigSet: !FindInMap [NotebookTypeToInitParams, !Ref NotebookType, ConfigSet]
      PropagateTagsToVolumeOnCreation: true
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
        - Key: Description
          Value: !Sub "Service Catalog instance created by ${AWS::StackName}"
        - Key: "ManagedInstanceMaintenanceTarget"
          Value: "yes"
        - Key: "PatchGroup"
          Value: "prod-default"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT20M

  EC2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W1011
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Port: 443
      Protocol: HTTPS
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      Targets:
      - Id: !Ref LinuxInstance
        Port: 443
      UnhealthyThresholdCount: 3
      VpcId: !ImportValue
          'Fn::FindInMap': [AccountToImportParams, !Ref "AWS::AccountId", VPCId]
      Tags:
      - Key: Name
        Value: !Sub 'TargetGroup-${LinuxInstance}'

  AlbListenerRule:
    Type: Custom::ALBListenerRule
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-alb-rule-FunctionArn'
      InstanceId: !Ref LinuxInstance
      TargetGroupArn: !Ref EC2TargetGroup
      ListenerArn: !ImportValue
        'Fn::Sub': '${AWS::Region}-alb-notebook-access-ALBListenerARN'
  TagInstance:
    DependsOn: "InstanceProfile"
    Type: Custom::SynapseTagger
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-synapse-tagger-SetInstanceTagsFunctionArn'
      InstanceId: !Ref LinuxInstance
Outputs:
  LinuxInstanceId:
    Description: 'The ID of the EC2 instance'
    Value: !Ref 'LinuxInstance'
  LinuxInstancePrivateIpAddress:
    Description: 'The IP Address of the EC2 instance'
    Value: !GetAtt 'LinuxInstance.PrivateIp'
  EC2InstanceType:
    Description: 'The EC2 instance type'
    Value: !Ref 'EC2InstanceType'
  ConnectionURI:
    Description: 'Starts a shell session in the AWS Console'
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/systems-manager/session-manager/${LinuxInstance}?region=${AWS::Region}"
  EC2ConsoleURI:
    Description: 'Check your instance status with this link to the AWS Console'
    Value: !Sub "https://console.aws.amazon.com/ec2/v2/home?region=${AWS::Region}#Instances:search=${LinuxInstance}"
  NotebookConnectionURI:
    Description: 'Notebook server login page'
    Value: !Sub
      - '${ALBConnectionURI}/${Path}/'
      - ALBConnectionURI: !ImportValue
          'Fn::Sub': '${AWS::Region}-alb-notebook-access-ConnectionURI'
        Path: !Ref LinuxInstance
  Documentation:
    Description: 'Service Catalog Documentation'
    Value: "https://help.sc.sageit.org/sc/Service-Catalog-Provisioning.938836322.html"
